blank_issues_enabled: false
contact_links:
  - name: 💬 Spectrum
    url: https://spectrum.chat/saleor
    about: If you have a support question or need help getting Saleor to work, please use our Spectrum.
