doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - django
autodetect: yes
ignore-paths:
    - docs
    - cms/migrations
    - cms/migrations_django
    - cms/tests/*
    - cms/test_utils/*
    - menus/migrations/*
    - menus/migrations_django/*