version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-graphql-jwt
    versions:
    - "> 0.3.0"
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: adyen
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: faker
    versions:
    - 7.0.1
  - dependency-name: django-countries
    versions:
    - "7.1"
  - dependency-name: mypy
    versions:
    - "0.812"
  - dependency-name: pytest-xdist
    versions:
    - 2.2.1
