version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3"
    rust: "1.55"

python:
   install:
      - requirements: requirements.txt
      - requirements: requirements-dev.txt
      - method: pip
        path: .

