# Make it explicit that we favor the
# new container-based Travis workers
language: python
dist: xenial
# Only used to install cibuildwheel, CIBW_BUILD determines the python version being
# built in the docker image itself. Also: travis does not have 3.10 yet.
python: 3.9

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache

env:
  global:
    - CPU_COUNT=3
    - TEST_DIR=/tmp/sklearn  # Test directory for continuous integration jobs
    - PYTEST_VERSION=latest
    - OMP_NUM_THREADS=2
    - OPENBLAS_NUM_THREADS=2
    - SKLEARN_BUILD_PARALLEL=3
    - SKLEARN_SKIP_NETWORK_TESTS=1
    - PYTHONUNBUFFERED=1
    # Custom environment variables for the ARM wheel builder
    - CIBW_BUILD_VERBOSITY=1
    - CIBW_TEST_COMMAND="bash {project}/build_tools/travis/test_wheels.sh"
    - CIBW_ENVIRONMENT="CPU_COUNT=4
                        OMP_NUM_THREADS=2
                        OPENBLAS_NUM_THREADS=2
                        SKLEARN_BUILD_PARALLEL=10
                        SKLEARN_SKIP_NETWORK_TESTS=1
                        PYTHONUNBUFFERED=1"

jobs:
  include:
    # Linux environments to build the scikit-learn wheels for the ARM64
    # architecture and Python 3.7 and newer. This is used both at release time
    # with the manual trigger in the commit message in the release branch and as
    # a scheduled task to build the weekly dev build on the main branch. The
    # weekly frequency is meant to avoid depleting the Travis CI credits too
    # fast.
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      if: type = cron or commit_message =~ /\[cd build\]/
      env:
        - CIBW_BUILD=cp37-manylinux_aarch64
        - BUILD_WHEEL=true

    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      if: type = cron or commit_message =~ /\[cd build\]/
      env:
        - CIBW_BUILD=cp38-manylinux_aarch64
        - BUILD_WHEEL=true

    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      if: type = cron or commit_message =~ /\[cd build\]/
      env:
        - CIBW_BUILD=cp39-manylinux_aarch64
        - BUILD_WHEEL=true

    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      if: type = cron or commit_message =~ /\[cd build\]/
      env:
        - CIBW_BUILD=cp310-manylinux_aarch64
        - BUILD_WHEEL=true

install: source build_tools/travis/install.sh || travis_terminate 1
script: source build_tools/travis/script.sh || travis_terminate 1
after_success: source build_tools/travis/after_success.sh || travis_terminate 1

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change
    on_failure: always
    on_start: never
